// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Boost: typeof import('./src/components/Boost.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    ChartIcon: typeof import('./src/components/ChartIcon.vue')['default']
    CustomIcon: typeof import('./src/components/CustomIcon.vue')['default']
    FacebookIcon: typeof import('./src/components/FacebookIcon.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FooterIcons: typeof import('./src/components/FooterIcons.vue')['default']
    GaugeIcon: typeof import('./src/components/GaugeIcon.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    InstagramIcon: typeof import('./src/components/InstagramIcon.vue')['default']
    LinkResult: typeof import('./src/components/LinkResult.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MenuIcon: typeof import('./src/components/MenuIcon.vue')['default']
    NavLink: typeof import('./src/components/NavLink.vue')['default']
    PageColumn: typeof import('./src/components/PageColumn.vue')['default']
    PinterestIcon: typeof import('./src/components/PinterestIcon.vue')['default']
    Shortener: typeof import('./src/components/Shortener.vue')['default']
    Statistics: typeof import('./src/components/Statistics.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TwitterIcon: typeof import('./src/components/TwitterIcon.vue')['default']
  }
}

export { }
